# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :Ameiurus do
  run_tests(scheme: "Ameiurus")
  if git_branch() == 'master'
    slack(message: 'Hello push version: ' + get_version_number())
    pod_push(path: 'LoremPlusPlusSwift.podspec')
  end
end
