# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ameiurus-melas' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Ameiurus-melas
  pod 'Alamofire', '~> 4.7'
  #Auto Layout library
  pod 'SnapKit', '~> 4.0.0'
  #library for downloading and caching images from API
  #pod 'Kingfisher', '~> 3.0'
  #Send Message TextInput
  pod 'Toolbar'
  #Messages TableView
  #pod 'ReverseExtension'



end

target 'Ameiurus-melasTests' do

  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  # Pods for testing
end

target 'SampleAmeiurus' do
  use_frameworks

end
